# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0006_auto_20160818_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token_key',
            field=models.CharField(db_index=True, default=b'', max_length=8),
        ),
    ]
